config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :simulations do
      get '/marcar-realizada', to: "simulations#marcar_realizada", as: "marcar_realizada"
    end
    resources :microinsulto_encuesta_inicials
    resources :microinsulto_encuesta_finals

    resources :microasalto_encuesta_inicials
    resources :microasalto_encuesta_finals

    resources :microinvalidacion_encuesta_inicials
    resources :microinvalidacion_encuesta_finals
  end

  resources :empresas do
    get '/new_user', to:"users#new", as: "new_user"
  end

  devise_scope :user do
    authenticated :user do
      root 'static#index', as: :authenticated_root
      post 'users/:id/edit', to: "users#update", as: "update_user"
      delete 'user/:id', to: "users#destroy", as: "destroy_user"
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get '/simulaciones', to: "static#simulaciones", as: "simulaciones"
  get '/global', to: "static#global", as: "global"
  get '/resultados/:user_id', to: "static#resultados", as: "resultados"
  get '/microinsulto/:user_id', to: "static#microinsulto", as: "microinsulto"
  get '/microasalto/:user_id', to: "static#microasalto", as: "microasalto"
  get '/microinvalidacion/:user_id', to: "static#microinvalidacion", as: "microinvalidacion"

  
  #API
  get "/api/show_user", to: "api#show_user", as: "api_show_user"
  get "/api/get_simulations", to: "api#get_simulations", as: "api_get_simulations"
  post "/api/simulacion_realizada", to: "api#simulacion_realizada", as: "api_simulacion_realizada"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/simulation.rb
class Simulation < ApplicationRecord

    belongs_to :user, foreign_key: "user_id"

    validates :tipo, presence: true
    validates :perspectiva, presence: true
    validates :realizada, presence: false


    def conducta_promedio
        promedio = 0
        decisiones = JSON.parse self.decisiones
        cant =  decisiones['cantidad'].to_i
        decisiones['conducta'].each do |conduct|
            promedio += conduct.to_i
        end
        
        promedio = promedio/cant
        
        case
        when promedio < 1
            0
        when promedio < 2
            1
        when promedio < 3
            2
        end

        promedio
    end

    
    def texto_decisiones
        decisiones = JSON.parse self.decisiones
        decisiones['texto']
    end
end

app/controllers/simulations_controller.rb
class SimulationsController < ApplicationController

    def show
        @simulation = Simulation.find(params[:id])
    end

    def new
        @user = User.find(params[:user_id])
    end

    def create
        @user = User.find(params[:user_id])
        @simulation = Simulation.new(create_params)
        @simulation.update(user_id: params[:user_id], realizada: false)

        if @simulation.save
            flash[:notice] = "Simulación de #{@simulation.tipo} como #{@simulation.perspectiva} asignada con éxito"
            
            redirect_to empresa_path(current_user.empresa_id)
        else
            flash[:alert] = @simulation.errors.full_messages.join(", ")
        end
    end

    def destroy
        user = User.find(params[:user_id])
        @simulation = Simulation.find(params[:simulation_id])
        if @simulation.destroy
            flash[:notice] = "Simulación de #{@simulation.tipo} como #{@simulation.perspectiva} eliminada con éxito"
        else
            flash[:alert] = @simulation.errors.full_messages.join(", ")
        end
        redirect_to empresa_path(user.empresa_id)
    end
    
    def marcar_realizada
        @simulation = @simulation = Simulation.find(params[:simulation_id])
        @simulation.update(realizada: true)

        if @simulation.save
            flash[:notice] = "Simulación de #{@simulation.tipo} como #{@simulation.perspectiva} realizada"
        else
            flash[:alert] = @simulation.errors.full_messages.join(", ")
        end
        redirect_to show_user_path(params[:user_id])
    end

    private

    def create_params
      params.require(:simulation).permit(:tipo, :perspectiva)
    end

end

app/helpers/simulations_helper.rb
module SimulationsHelper
end

app/views/simulations/_delete.html.erb
<!-- Modal toggle -->
<button class="block text-red-700 hover:text-white border border-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-600 dark:focus:ring-red-900" type="button" data-modal-toggle="defaultModal2<%= user.id %>">
Eliminar
</button>

<!-- Main modal -->
<div id="defaultModal2<%= user.id %>" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full">
    <div class="relative p-4 w-full max-w-2xl h-full md:h-auto">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <!-- Modal header -->
            <div class="flex justify-between items-start p-4 rounded-t border-b dark:border-gray-600">
                <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
                    Eliminar Simulación
                </h3>
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="defaultModal2<%= user.id %>">
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            
            <div class="p-6 space-y-6">
                <ul>
                    <% user.simulaciones.each do |simulacion| %>
                        <% if !simulacion.realizada %>
                            <li class ="flex flex-row items-center justify-between w-1/2 mx-auto mb-2"> 
                            <div class ="col-8">
                                <%= "#{simulacion.tipo} como #{simulacion.perspectiva}" %>
                            </div>
                            <div class ="col-4">
                                <%= button_to "x", user_simulation_path(user_id: user.id, simulation_id: simulacion.id), method: :delete, class: "font-bold block text-red-700 hover:text-white border border-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-2.5 py-0.5 text-center mr-2 mb-2 dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-600 dark:focus:ring-red-900 float-right" %>
                            </div> 
                            </li> 
                        <% end %> 
                    <% end %>
                <ul>


            </div>
            <!-- Modal footer -->
            <div class="flex items-center p-6 space-x-2 rounded-b border-t border-gray-200 dark:border-gray-600">
                <div class="float-right" >
                    <%= link_to "Volver", :back,  class:"float-right text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600"%>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/simulations/_new.html.erb
<!-- Modal toggle -->
<button class="block text-white hover:text-gray-900 border border-gray-900 bg-gray-800 hover:bg-white focus:ring-4 focus:outline-none focus:ring-gray-600 font-medium rounded-lg text-sm px-5 py-2.5 text-center mb-4" type="button" data-modal-toggle="defaultModal<%= user.id %>">
Asignar
</button>

<!-- Main modal -->
<div id="defaultModal<%= user.id %>" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full">
    <div class="relative p-4 w-full max-w-2xl h-full md:h-auto">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <%= form_for :simulation, url: user_simulations_path(user_id: user.id), method: :post do |f| %>
            <!-- Modal header -->
            <div class="flex justify-between items-start p-4 rounded-t border-b dark:border-gray-600">
                <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
                    Asignar Simulación
                </h3>
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="defaultModal<%= user.id %>">
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            
            <div class="p-6 space-y-6">
                    <div class="w-full">
                        <%= f.select :tipo, ["Microinsulto", "Microasalto", "Microinvalidacion"], {} %>
                    </div>

                    <div class="w-full">
                        <%= f.select :perspectiva, ["Testigo", "Victima", "Victimario"], {} %>
                    </div>
            </div>
            <!-- Modal footer -->
            <div class="flex items-center p-6 space-x-2 rounded-b border-t border-gray-200 dark:border-gray-600">
                <div>
                    <%= f.submit "Añadir", class:"text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
                    <%= link_to "Volver", :back,  class:"float-right text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600"%>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/simulations/show.html.erb
<%= "#{@simulation.tipo} como #{@simulation.perspectiva}"%>