config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :simulations do
      get '/marcar-realizada', to: "simulations#marcar_realizada", as: "marcar_realizada"
    end
    resources :microinsulto_encuesta_inicials
    resources :microinsulto_encuesta_finals

    resources :microasalto_encuesta_inicials
    resources :microasalto_encuesta_finals

    resources :microinvalidacion_encuesta_inicials
    resources :microinvalidacion_encuesta_finals
  end

  resources :empresas do
    get '/new_user', to:"users#new", as: "new_user"
  end

  devise_scope :user do
    authenticated :user do
      root 'static#index', as: :authenticated_root
      post 'users/:id/edit', to: "users#update", as: "update_user"
      delete 'user/:id', to: "users#destroy", as: "destroy_user"
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get '/simulaciones', to: "static#simulaciones", as: "simulaciones"
  get '/global', to: "static#global", as: "global"
  get '/resultados/:user_id', to: "static#resultados", as: "resultados"
  get '/microinsulto/:user_id', to: "static#microinsulto", as: "microinsulto"
  get '/microasalto/:user_id', to: "static#microasalto", as: "microasalto"
  get '/microinvalidacion/:user_id', to: "static#microinvalidacion", as: "microinvalidacion"

  
  #API
  get "/api/show_user", to: "api#show_user", as: "api_show_user"
  get "/api/get_simulations", to: "api#get_simulations", as: "api_get_simulations"
  post "/api/simulacion_realizada", to: "api#simulacion_realizada", as: "api_simulacion_realizada"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  belongs_to :empresa, class_name: "empresa", foreign_key: "empresa_id", optional: true
  has_one :microinsulto_encuesta_inicial, dependent: :destroy
  has_one :microinsulto_encuesta_final, dependent: :destroy

  has_one :microasalto_encuesta_inicial, dependent: :destroy
  has_one :microasalto_encuesta_final, dependent: :destroy

  has_one :microinvalidacion_encuesta_inicial, dependent: :destroy
  has_one :microinvalidacion_encuesta_final, dependent: :destroy
  
  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :telefono, presence: true, numericality: { only_integer: true}, length: {minimum:9, maximum:9}
  validates :encargado, presence: false
  validates :admin, presence: false

  def empresa
    Empresa.find(self.empresa_id)
  end

  #Simulaciones

  def simulaciones
    Simulation.where(user_id: self.id).all
  end

  def simulaciones_realizadas
    Simulation.where(user_id: self.id).where(realizada: true).all
  end

  def simulaciones_pendientes
    Simulation.where(user_id: self.id).where(realizada: false).all
  end

  #Encuestas
  def microinsulto_encuesta_inicial
    MicroinsultoEncuestaInicial.find_by(user_id: self.id)
  end

  def microinsulto_encuesta_final
    MicroinsultoEncuestaFinal.find_by(user_id: self.id)
  end

  def microasalto_encuesta_inicial
    MicroasaltoEncuestaInicial.find_by(user_id: self.id)
  end

  def microasalto_encuesta_final
    MicroasaltoEncuestaFinal.find_by(user_id: self.id)
  end

  def microinvalidacion_encuesta_inicial
    MicroinvalidacionEncuestaInicial.find_by(user_id: self.id)
  end

  def microinvalidacion_encuesta_final
    MicroinvalidacionEncuestaFinal.find_by(user_id: self.id)
  end

  #Simulacion x tipo
  def simulaciones_microinsulto_realizadas
    Simulation.where(user_id: self.id).where(tipo: "Microinsulto").where(realizada: true).all
  end

  def simulaciones_microinsulto_pendientes
    Simulation.where(user_id: self.id).where(tipo: "Microinsulto").where(realizada: false).all
  end

  def simulaciones_microasalto_realizadas
    Simulation.where(user_id: self.id).where(tipo: "Microasalto").where(realizada: true).all
  end

  def simulaciones_microasalto_pendientes
    Simulation.where(user_id: self.id).where(tipo: "Microasalto").where(realizada: false).all
  end

  def simulaciones_microinvalidacion_realizadas
    Simulation.where(user_id: self.id).where(tipo: "Microinvalidacion").where(realizada: true).all
  end

  def simulaciones_microinvalidacion_pendientes
    Simulation.where(user_id: self.id).where(tipo: "Microinvalidacion").where(realizada: false).all
  end


  #Contadores
  def contador_decisiones(perspectiva, conducta)
    simulaciones = Simulation.where(user_id: self.id).where(perspectiva:perspectiva).where(realizada: true).all
    if simulaciones.nil?
      -1
    else
      contador = 0
      total = 0
      simulaciones.each do |simulacion|
        json= JSON.parse simulacion.decisiones
        conductas= json['conducta']
        conductas.each{|c| c == conducta ? contador += 1 : 0}
        total += conductas.count
      end
  
      contador/total.to_f

    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    load_and_authorize_resource

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new()
        @empresa = Empresa.find(params[:empresa_id])
    end

    def create
        @user = User.new(create_params)
        @user.empresa_id = params[:empresa_id]
        if @user.save
            flash[:notice] = "#{@user.nombre} #{@user.apellido} ha sido añadido con exito"
        else
            flash[:alert] = @user.errors.full_messages.join(', ')
            
        end
        redirect_to empresa_path(params[:empresa_id])
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(create_params)

        if @user.save
            flash[:notice] = "Usuario modificado con exito"
            redirect_to user_path
        else
            flash[:alert] = @user.errors.full_messages.join(', ')
            redirect_to edit_user_path
        end
    end

    def destroy
        @user = User.find(params[:id])
        empresa = Empresa.find(@user.empresa_id)
        name = @user.nombre
        if @user.destroy
            flash[:notice] = "#{name} se ha eliminado con exito"
            redirect_to empresa_path(empresa.id)
        else
            flash[:alert] = "No se pudo eliminar #{name}"
            redirect_to show_user_path
        end
    end

    private

    def create_params
        params.require(:user).permit(:nombre, :email, :apellido, :telefono, :encargado, :password, :password_confirmation)
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class='container'>
  <h2>Editar Trabajador</h2>
  <br/>

  <%= form_for :user,  url: update_user_path, method: :post do |f| %>
    
    <div class="field">
      <%= f.label :nombre, class: "form-label"%><br />
      <%= f.text_field :nombre, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="field">
      <%= f.label :apellido, class: "form-label" %><br />
      <%= f.text_field :apellido, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="field">
      <%= f.label :email, class: "form-label" %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="field">
      <%= f.label :telefono, class: "form-label" %><br />
      <%= f.text_field :telefono, autofocus: true, autocomplete: "phone" %>
    </div>


    <% if current_user.admin%>
      <div class="field">
        <%= f.label :encargado, "Encargado: " %>
        <%= f.check_box :encargado, {:class => "form-check-input"}, 'true', 'false' %>
      </div>
      <br/>
    <% end %>

    <div class="actions">
      <%= f.submit "Editar", class: 'btn btn-primary' %>
      <%= link_to "Volver", :back, class: 'btn btn-secondary' %>
    </div>
    <br/>
  <% end %>
</div>


 

app/views/users/new.html.erb
<div class ="container">
  <h2 class="text-2xl font-extrabold dark:text-white my-4">Datos</h2>

  <%= form_for :user,  url: users_path(empresa_id: @empresa.id), method: :post do |f| %>
    
    <div class="field mb-4">
      <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Nombre</label>
      <%= f.text_field :nombre, autofocus: true, autocomplete: "name", class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light" %>
    </div>

    <div class="field mb-4">
      <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Apellido</label>
      <%= f.text_field :apellido, autofocus: true, autocomplete: "name", class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light" %>
    </div>

    <div class="field mb-4">
      <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Email</label>
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light" %>
    </div>

    <div class="field mb-4">
      <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Telefono</label>
      <%= f.text_field :telefono, autofocus: true, autocomplete: "phone", class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light" %>
    </div>

    <div class="field mb-4">
      <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Contraseña</label>
      <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %>
      <%= f.password_field :password, autocomplete: "new-password", class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light" %>
    </div>

    <div class="field mb-4">
      <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Confirmar contraseña</label>
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light" %>
    </div>
    <br/>

    <% if current_user.admin %>
      <div class="field mb-4">
        <%= f.label :encargado, "Encargado: " %>
        <%= f.check_box :encargado, {:class => "form-check-input"}, 'true', 'false' %>
      </div>
    <% end %>

    <div class="actions">
      <%= f.submit "Añadir", class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' %>
      <%= link_to "Volver", :back, class: "text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-600 dark:focus:ring-blue-800 float-right" %>
    </div>
    <br/>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= "#{@user.nombre} #{@user.apellido}" %></h1>

<% if current_user.id == @user.id%>
    <%= link_to "Editar Perfil", edit_user_path(current_user.id) %>
<% else %>
    <% if can? :edit, User %>
        <%= link_to "Editar Usuario", edit_user_path(id: @user.id) %>
    <% end %>
<% end %>


<% if can? :destroy, User %>
    <%= button_to "Eliminar Usuario", destroy_user_path(id: @user.id), method: :delete %>
<% end %>