config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :simulations do
      get '/marcar-realizada', to: "simulations#marcar_realizada", as: "marcar_realizada"
    end
    resources :microinsulto_encuesta_inicials
    resources :microinsulto_encuesta_finals

    resources :microasalto_encuesta_inicials
    resources :microasalto_encuesta_finals

    resources :microinvalidacion_encuesta_inicials
    resources :microinvalidacion_encuesta_finals
  end

  resources :empresas do
    get '/new_user', to:"users#new", as: "new_user"
  end

  devise_scope :user do
    authenticated :user do
      root 'static#index', as: :authenticated_root
      post 'users/:id/edit', to: "users#update", as: "update_user"
      delete 'user/:id', to: "users#destroy", as: "destroy_user"
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get '/simulaciones', to: "static#simulaciones", as: "simulaciones"
  get '/global', to: "static#global", as: "global"
  get '/resultados/:user_id', to: "static#resultados", as: "resultados"
  get '/microinsulto/:user_id', to: "static#microinsulto", as: "microinsulto"
  get '/microasalto/:user_id', to: "static#microasalto", as: "microasalto"
  get '/microinvalidacion/:user_id', to: "static#microinvalidacion", as: "microinvalidacion"

  
  #API
  get "/api/show_user", to: "api#show_user", as: "api_show_user"
  get "/api/get_simulations", to: "api#get_simulations", as: "api_get_simulations"
  post "/api/simulacion_realizada", to: "api#simulacion_realizada", as: "api_simulacion_realizada"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/empresa.rb
class Empresa < ApplicationRecord

    validates :nombre, presence: true
    validates :direccion, presence: true
    validates :comuna, presence: true
    validates :region, presence: true
    validates :rut, presence: false

    has_many :users, dependent: :destroy

    #---------Empleados------------
    def empleados
        User.where(empresa_id: self.id).where(encargado: false).all
    end

    def encargados
        User.where(empresa_id: self.id).where(encargado: true).all
    end

    #----------------Encuestas-----------------
    def promedio_encuesta_inicial_microinsulto
        promedio = 0
        encuestas_iniciales = []
        self.empleados.each do |empleado|
            if !empleado.microinsulto_encuesta_inicial.nil?
                encuestas_iniciales << empleado.microinsulto_encuesta_inicial
            end
        end
        if !encuestas_iniciales.empty?
            cant_encuestas = encuestas_iniciales.length()
            suma = 0
            encuestas_iniciales.each do |encuesta|
                suma += encuesta.porcentaje_bueno
            end
            promedio = suma/cant_encuestas
        else
            0
        end
    end

    def promedio_encuesta_final_microinsulto
        promedio = 0
        encuestas_finales = []
        self.empleados.each do |empleado|
            if !empleado.microinsulto_encuesta_final.nil?
                encuestas_finales << empleado.microinsulto_encuesta_final
            end
        end
        if !encuestas_finales.empty?
            cant_encuestas = encuestas_finales.length()
            suma = 0
            encuestas_finales.each do |encuesta|
                suma += encuesta.porcentaje_bueno
            end
            promedio = suma/cant_encuestas
        else
            0
        end
    end

    def promedio_encuesta_inicial_microasalto
        promedio = 0
        encuestas_iniciales = []
        self.empleados.each do |empleado|
            if !empleado.microasalto_encuesta_inicial.nil?
                encuestas_iniciales << empleado.microasalto_encuesta_inicial
            end
        end
        if !encuestas_iniciales.empty?
            cant_encuestas = encuestas_iniciales.length()
            suma = 0
            encuestas_iniciales.each do |encuesta|
                suma += encuesta.porcentaje_bueno
            end
            promedio = suma/cant_encuestas
        else
            0
        end
    end

    def promedio_encuesta_final_microasalto
        promedio = 0
        encuestas_iniciales = []
        self.empleados.each do |empleado|
            if !empleado.microasalto_encuesta_final.nil?
                encuestas_iniciales << empleado.microasalto_encuesta_final
            end
        end
        if !encuestas_iniciales.empty?
            cant_encuestas = encuestas_iniciales.length()
            suma = 0
            encuestas_iniciales.each do |encuesta|
                suma += encuesta.porcentaje_bueno
            end
            promedio = suma/cant_encuestas
        else
            0
        end
    end

    def promedio_encuesta_inicial_microinvalidacion
        promedio = 0
        encuestas_iniciales = []
        self.empleados.each do |empleado|
            if !empleado.microinvalidacion_encuesta_inicial.nil?
                encuestas_iniciales << empleado.microinvalidacion_encuesta_inicial
            end
        end
        if !encuestas_iniciales.empty?
            cant_encuestas = encuestas_iniciales.length()
            suma = 0
            encuestas_iniciales.each do |encuesta|
                suma += encuesta.porcentaje_bueno
            end
            promedio = suma/cant_encuestas
        else
            0
        end
    end

    def promedio_encuesta_final_microinvalidacion
        promedio = 0
        encuestas_iniciales = []
        self.empleados.each do |empleado|
            if !empleado.microinvalidacion_encuesta_final.nil?
                encuestas_iniciales << empleado.microinvalidacion_encuesta_final
            end
        end
        if !encuestas_iniciales.empty?
            cant_encuestas = encuestas_iniciales.length()
            suma = 0
            encuestas_iniciales.each do |encuesta|
                suma += encuesta.porcentaje_bueno
            end
            promedio = suma/cant_encuestas
        else
            0
        end
    end


    #----------------Simulaciones--------------------
    def cantidad_simulaciones_realizadas
        count = 0
        self.empleados.map{|empleado| count = count + empleado.simulaciones_realizadas.count}
        count
    end

    def cantidad_simulaciones_pendientes
        count = 0
        self.empleados.map{|empleado| count = count + empleado.simulaciones_pendientes.count}
        count
    end

    #--------------Tendecia de conductas------------------
    def conducta_general
        promedio = 0
        simulaciones = self.empleados.map{|empleado| empleado.simulaciones_realizadas}.flatten

        conductas = simulaciones.each{|simulacion| promedio += simulacion.conducta_promedio }
        promedio = promedio/simulaciones.count
    end

    def contador_decisiones(perspectiva,conducta)
        contador = 0
        total = 0
        self.empleados.each do |empleado|
            simulaciones = Simulation.where(user_id: empleado.id).where(perspectiva:perspectiva).where(realizada: true).all
            if !simulaciones.nil?
                simulaciones.each do |simulacion|
                    json= JSON.parse simulacion.decisiones
                    conductas= json['conducta']
                    conductas.each{|c| c == conducta ? contador += 1 : 0}
                    total += conductas.count
                end
            end
        end
        contador/total.to_f
    end

    def presencia_microinsultos
        yes = 0
        no = 0
        not_sure = 0
        total = 0 

        self.empleados.each do |empleado|
            if !empleado.microinsulto_encuesta_inicial.nil?
                case empleado.microinsulto_encuesta_inicial.pregunta7
                when nil
                    not_sure += 1
                when true
                    yes += 1
                when false
                    no += 1
                end
                total += 1
            end
        end
        resultados = [yes,no,not_sure, total]
    end

    def presencia_microasaltos
        yes = 0
        no = 0
        not_sure = 0
        total = 0 

        self.empleados.each do |empleado|
            if !empleado.microasalto_encuesta_inicial.nil?
                case empleado.microasalto_encuesta_inicial.pregunta7
                when nil
                    not_sure += 1
                when true
                    yes += 1
                when false
                    no += 1
                end
                total += 1
            end
        end
        resultados = [yes,no,not_sure, total]
    end

    def presencia_microinvalidaciones
        yes = 0
        no = 0
        not_sure = 0
        total = 0 

        self.empleados.each do |empleado|
            if !empleado.microinvalidacion_encuesta_inicial.nil?
                case empleado.microinvalidacion_encuesta_inicial.pregunta7
                when nil
                    not_sure += 1
                when true
                    yes += 1
                when false
                    no += 1
                end
                total += 1
            end
        end
        resultados = [yes,no,not_sure, total]
    end
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
    before_action :authenticate_user!
    load_and_authorize_resource

    def show
        @empresa = Empresa.find(params[:id])
    end

    def index
        @empresas = Empresa.all
    end

    def def new
        @empresa = Empresa.new()
    end
    
    def create
        @empresa = Empresa.new(create_params)
        
        if @empresa.save
            flash[:notice] = "#{@empresa.nombre} ha sido creada con exito"
            redirect_to empresas_path
        else
            flash[:alert] = @empresa.errors.full_messages.join(', ')
            redirect_to new_empresa_path
        end
    end

    def edit
        @empresa = Empresa.find(params[:id])
    end

    def update
        @empresa = Empresa.find(params[:id])
        @empresa.update(create_params)

        if @empresa.save
            flash[:notice] = "#{@empresa.nombre} ha sido actualizada con exito"
            redirect_to empresa_path(id: @empresa.id)
        else
            flash[:alert] = @empresa.errors.full_messages.join(', ')
            redirect_to edit_empresa_path
        end
    end

    def destroy
        @empresa = Empresa.find(params[:id])
        name = @empresa.nombre
        if @empresa.destroy
            flash[:notice] = "#{name} se ha eliminado con exito"
            redirect_to empresas_path
        else
            flash[:alert] = "No se pudo eliminar #{name}"
            redirect_to empresa_path(params[:id])
        end
    end

    private

    def create_params
      params.require(:empresa).permit(:nombre, :direccion, :comuna, :oficina, :region)
    end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/edit.html.erb
<div class='container'>

    <h1>Editar Empresa</h1><br/>

    <%= form_for :empresa, url: empresa_path, method: :patch do |f| %>

        <div >
            <%= f.label :nombre %><br>
            <%= f.text_field :nombre %>
        </div>

        <div>
            <%= f.label :rut %><br>
            <%= f.text_field :rut %>
        </div>

        <div>
            <%= f.label :direccion %><br>
            <%= f.text_field :direccion %>
        </div>

        <div class=" col-4">
            <%= f.label :oficina %><br>
            <%= f.text_field :oficina %>
        </div>

        <div>
            <%= f.label :region %><br>
            <%= f.select :region, ["Region Metropolitana"], {} %>
        </div>
        
        <div>
        <%= f.label :comuna %><br>
            <%= f.select :comuna, ["Santiago","Conchalí","Huechuraba","Independencia",
            "Quilicura","Recoleta","Renca","Las Condes","Lo Barnechea","Providencia",
            "Vitacura","La Reina","Macul","Ñuñoa","Peñalolén","La Florida","La Granja",
            "El Bosque","La Cisterna","La Pintana","San Ramón","Lo Espejo","Pedro Aguirre Cerda",
            "San Joaquín","San Miguel","Cerrillos","Estación Central","Maipú","Cerro Navia","Lo Prado",
            "Pudahuel","Quinta Normal"],
            {} %>
        </div>
        
        <div >
            <%= f.submit "Editar" %>
            <%= link_to "Volver", :back%>
        </div>

    <% end %>
</div>

app/views/empresas/index.html.erb
    <h1>Empresas</h1>

    <% @empresas.each do |empresa| %>
        <h2><%= link_to empresa.nombre, empresa_path(empresa.id) %></h2>
        <h4><%= "Direccion: #{empresa.direccion}" %></h4>
        <% if !empresa.oficina.empty? %>
            <h4><%= "Oficina: #{empresa.oficina}" %></h4>
        <%  end %>
        <h4><%= "Comuna: #{empresa.comuna}" %></h4>
        <br/>
    <% end %>

 
    <div>
        <%= link_to "Añadir Empresa", new_empresa_path%>
    </div>

app/views/empresas/new.html.erb
<div class='container'>

    <h1>Añadir Empresa</h1><br/>

    <%= form_for :empresa, url: empresas_path, method: :post do |f| %>

        <div class="field">
            <%= f.label :nombre %><br>
            <%= f.text_field :nombre %>
        </div>

        <div class="field">
            <%= f.label :rut%><br>
            <%= f.text_field :rut %>
        </div>

        <div class="field">
            <%= f.label :direccion, class: "form-label" %><br>
            <%= f.text_field :direccion, class: "form-control" %>
        </div>

        <div class="field">
            <%= f.label :oficina, class: "form-label" %><br>
            <%= f.text_field :oficina, class: "form-control" %>
        </div>

        <div class="field">
            <%= f.label :region %><br>
            <%= f.select :region, ["Region Metropolitana"], {}%>
        </div>
        
        <div class="field">
        <%= f.label :comuna %><br>
            <%= f.select :comuna, ["Santiago","Conchalí","Huechuraba","Independencia",
            "Quilicura","Recoleta","Renca","Las Condes","Lo Barnechea","Providencia",
            "Vitacura","La Reina","Macul","Ñuñoa","Peñalolén","La Florida","La Granja",
            "El Bosque","La Cisterna","La Pintana","San Ramón","Lo Espejo","Pedro Aguirre Cerda",
            "San Joaquín","San Miguel","Cerrillos","Estación Central","Maipú","Cerro Navia","Lo Prado",
            "Pudahuel","Quinta Normal"],
            {}%>
        </div>
        
        <div>
            <%= f.submit "Añadir Empresa" %>
            <%= link_to "Volver", :back%>
        </div>

    <% end %>
</div>

app/views/empresas/show.html.erb
<h2 class="text-4xl font-extrabold dark:text-white mb-4">Mi Empresa</h2>

<p class="text-lg text-gray-500"><%= "Nombre: #{@empresa.nombre}" %></p>
<p class="text-lg text-gray-500 mb-4">
    Dirección: 
    <%= @empresa.direccion %>,
    <% if !@empresa.oficina.empty? %>
            <%= "Of. #{@empresa.oficina}" %>,
    <% end %>
    <%= @empresa.comuna %>.
</p>

<h2 class="text-2xl font-extrabold dark:text-white my-4">Listado de Empleados</h2>

<% if @empresa.empleados.empty?%>
    <p>No hay nada aqui todavia</p>
<% else %>

    <div class="overflow-x-auto relative shadow-md sm:rounded-lg mb-5">
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                    <th scope="col" class="py-3 px-6">
                        Nombre
                    </th>
                    <th scope="col" class="py-3 px-6">
                        Cargo
                    </th>
                    <th scope="col" class="py-3 px-6">
                        Simulaciones Realizadas
                    </th>
                    <th scope="col" class="py-3 px-6">
                        Simulaciones Pendientes
                    </th>
                    <th scope="col" class="py-3 px-6">
                        Acciones
                    </th>
                </tr>
            </thead>
            <% @empresa.empleados.each do |empleado| %>
                <tbody>
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                        <th class="py-4 px-6">
                            <div class ="flex items-center py-4 px-6 text-gray-900 whitespace-nowrap dark:text-white">
                                <img class="w-10 h-10 rounded-full" src="/images/avatar2.png" alt="Jese image">
                                <div class="pl-3">
                                    <div class="text-base font-semibold"><%= link_to "#{empleado.nombre} #{empleado.apellido} ", user_path(empleado.id)%> </div>
                                    <div class="font-normal text-gray-500"><%= empleado.email %></div>
                                </div> 
                            </div> 
                        </th>
                        <td class="py-4 px-6">
                            React Developer
                        </td>
                        <td class="py-4 px-6">
                            <% if empleado.simulaciones_realizadas.empty?%>
                                No ha realizado simulaciones
                            <% else %>
                                <ul>
                                <% empleado.simulaciones_realizadas.each do |simulacion| %>
                                    
                                    <li class ="text-green-600"><%= "#{simulacion.tipo} como #{simulacion.perspectiva}" %></li>
                                <% end %>
                                </ul>
                            <% end %>
                        </td>
                        <td class="py-4 px-6">
                            <% if empleado.simulaciones_pendientes.empty?%>
                                No hay simulaciones pendientes
                            <% else %>
                                <ul>
                                <% empleado.simulaciones_pendientes.each do |simulacion| %>
                                    
                                    <li><%= "#{simulacion.tipo} como #{simulacion.perspectiva}" %></li>
                                <% end %>
                                </ul>
                            <% end %>
                        </td>
                        <td class="py-4 px-6 empleados-actions">
                            <button>
                                <%= link_to "Ver", resultados_path(empleado.id), class: "block text-white hover:text-green-900 border border-green-900 bg-green-800 hover:bg-white focus:ring-4 focus:outline-none focus:ring-green-600 font-medium rounded-lg text-sm px-5 py-2.5 text-center mb-4"%>
                            </button>
                            <%= render "simulations/new", {:user => empleado}%>
                            <% if !empleado.simulaciones_pendientes.empty? %>
                                <%= render "simulations/delete", {:user => empleado}%>
                            <% end %>

                        </td>
                    </tr>
                </tbody>
            <% end %>
        </table>
    </div>
    <% end %>


<div>
    <% if can? :new, User %>
        <%= link_to "Añadir Empleado", empresa_new_user_path(empresa_id: @empresa.id), 
        class: "text-white hover:text-blue-900 border border-blue-900 bg-blue-800 hover:bg-white focus:ring-4 focus:outline-none focus:ring-blue-600 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 mb-5 float-right"%>
    <% end%>
    
    <% if can? :manage, Empresa %>
        <%= link_to "Volver", empresas_path %> <br/>
    <% end %>
    
    <% if can? :edit, Empresa %>
        <%= link_to "Editar", edit_empresa_path %>
    <% end%>

    <% if can? :delete, Empresa %>
        <div style="display:inline-block;">
            <%= button_to "Eliminar", empresa_path(@empresa.id), method: :delete %>
        </div>
    <% end%>
</div>