config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :simulations do
      get '/marcar-realizada', to: "simulations#marcar_realizada", as: "marcar_realizada"
    end
    resources :microinsulto_encuesta_inicials
    resources :microinsulto_encuesta_finals

    resources :microasalto_encuesta_inicials
    resources :microasalto_encuesta_finals

    resources :microinvalidacion_encuesta_inicials
    resources :microinvalidacion_encuesta_finals
  end

  resources :empresas do
    get '/new_user', to:"users#new", as: "new_user"
  end

  devise_scope :user do
    authenticated :user do
      root 'static#index', as: :authenticated_root
      post 'users/:id/edit', to: "users#update", as: "update_user"
      delete 'user/:id', to: "users#destroy", as: "destroy_user"
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get '/simulaciones', to: "static#simulaciones", as: "simulaciones"
  get '/global', to: "static#global", as: "global"
  get '/resultados/:user_id', to: "static#resultados", as: "resultados"
  get '/microinsulto/:user_id', to: "static#microinsulto", as: "microinsulto"
  get '/microasalto/:user_id', to: "static#microasalto", as: "microasalto"
  get '/microinvalidacion/:user_id', to: "static#microinvalidacion", as: "microinvalidacion"

  
  #API
  get "/api/show_user", to: "api#show_user", as: "api_show_user"
  get "/api/get_simulations", to: "api#get_simulations", as: "api_get_simulations"
  post "/api/simulacion_realizada", to: "api#simulacion_realizada", as: "api_simulacion_realizada"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/microasalto_encuesta_final.rb
class MicroasaltoEncuestaFinal < ApplicationRecord
    belongs_to :user, foreign_key: "user_id"

    def cant_preguntas_buenas
        buenas = 0
        if self.pregunta1 == true
            buenas += 1
        end
        if self.pregunta2 == true
            buenas += 1
        end
        if self.pregunta3 == true
            buenas += 1
        end
        buenas
    end

    def porcentaje_bueno
        self.cant_preguntas_buenas * 100 / 3
    end
end

app/controllers/microasalto_encuesta_finals_controller.rb
class MicroasaltoEncuestaFinalsController < ApplicationController
    def show
        @encuesta = MicroasaltoEncuestaFinal.find(params[:id])
        @user = User.find(params[:user_id])
    end

    def new
        @user = User.find(params[:user_id])
        if !@user.microasalto_encuesta_final.nil?
            flash[:alert] = "Ya has realizado la encuesta inicial"
            redirect_to simulaciones_path
        end
        @encuesta = MicroasaltoEncuestaFinal.new()
    end

    def create
        @user = User.find(params[:user_id])
        if !@user.microasalto_encuesta_final.nil?
            flash[:alert] = "Ya has realizado la encuesta final"
            redirect_to Microasalto_path(@user.id)
        end
        @encuesta = MicroasaltoEncuestaFinal.new(create_params)
        @encuesta.update(user_id: params[:user_id])

        if @encuesta.save
            flash[:notice] = "Encuesta completada con exito"
            redirect_to user_microasalto_encuesta_final_path(user_id: @user, id: @encuesta.id)
        else
            flash[:alert] = @encuesta.errors.full_messages.join(', ')
        end
    end

    private

    def create_params
        if params.has_key?(:microasalto_encuesta_final)
            params.fetch(:microasalto_encuesta_final)
            .permit(:pregunta1, :pregunta2, :pregunta3, :pregunta4)
        end
    end
end

app/helpers/microasalto_encuesta_finals_helper.rb
module MicroasaltoEncuestaFinalsHelper
end

app/views/microasalto_encuesta_finals/new.html.erb
<div class='container text-center'>
    <h2 class="text-4xl font-extrabold dark:text-white mb-4">Encuesta Final de Microasalto</h2>

<%= form_for :microasalto_encuesta_final, url: user_microasalto_encuesta_finals_path(current_user.id), method: :post do |f| %>
    <!-- multistep form -->
    <div id="form-microasalto-final">
        <!-- progressbar -->
        <ul id="progressbar-microasalto-final">
            <li class="active"></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
        <!-- fieldsets -->
        <fieldset>
            <h2 class="fs-title">Instrucciones</h2>
            <div class="mb-5">
                Lee atentamente las preguntas y responde según lo que consideres correcto.<br/>
                <b>[Confidencialidad]</b> Recuerda que los resultados se mostrarán de forma general y no en detalle.</b>             </div>
            <input type="button" name="next" class="next-microasalto-final" value="Siguiente" />
        </fieldset>
        <fieldset>
            <h2 class="fs-title">Pregunta 1</h2>
            <h3 class="fs-subtitle">De acuerdo a la simulación, ¿qué crees que se pudo evidenciar?</h3>

            <div class ="field-buttons">
                <div class="radio-button"> <%= f.radio_button :pregunta1, false %> a) Comentario o acción discriminatoria de manera sutil.</div>
                <div class="radio-button"> <%= f.radio_button :pregunta1, true %> b) Comportamiento intencional y discriminatorio sin pretensión de ofensa. </div>
                <div class="radio-button"> <%= f.radio_button :pregunta1, false %> c) Minimización de experiencias ajenas. </div>
                <div class="radio-button"> <%= f.radio_button :pregunta1, false %> d) No hubo ningún comentario o acción inadecuada. </div>
            </div> 
    
            <input type="button" name="previous" class="previous-microasalto-final" value="Atrás" />
            <input type="button" name="next" class="next-microasalto-final" value="Siguiente" />
        </fieldset>
        <fieldset>

            <h2 class="fs-title">Pregunta 2</h2>
            <h3 class="fs-subtitle"> Teniendo bajo consideración lo siguiente:</h3>
            <b class="text-left">
            I. Comportamientos intencionales y discriminatorios sin pretensión de ofensa.<br/>
            II. Menospreciar o invalidar experiencias ajenas.<br/>
            III. Comentarios o acciones que son discriminatorias accidentalmente.<br/>
            En la/s simulación/es realizada/s recientemente, cuál definición describe de mejor manera lo que usted experimentó:
            </b><br/>
            <div class ="field-buttons">
                <div class="radio-button"><%= f.radio_button :pregunta2, true %>Solo I</div>
                <div class="radio-button"><%= f.radio_button :pregunta2, false %>Solo II</div>
                <div class="radio-button"><%= f.radio_button :pregunta2, false %>Solo III</div>
                <div class="radio-button"><%= f.radio_button :pregunta2, false %>I y II</div>
                <div class="radio-button"><%= f.radio_button :pregunta2, false %>I y III</div>
                <div class="radio-button"><%= f.radio_button :pregunta2, false %>Ninguna de las anteriores</div>
            </div> 

            <input type="button" name="previous" class="previous-microasalto-final" value="Atrás" />
            <input type="button" name="next" class="next-microasalto-final" value="Siguiente" />
        </fieldset>
        <fieldset>
            <h2 class="fs-title">Pregunta 3</h2>
            <h3 class="fs-subtitle">¿Quién consideras que fue la persona agredida la/s simulación/es realizada/s?</h3>

            
            <div class ="field-buttons">
                <b class="mb-3">Víctima:</b>
                <div class="radio-button"> <%= f.radio_button :pregunta3, true %> a) Yo, fui la víctima de la simulación.</div>
                <div class="radio-button"> <%= f.radio_button :pregunta3, false %> b) Cristian, el gerente de la empresa. </div>
                <div class="radio-button"> <%= f.radio_button :pregunta3, false %> c) Jimena, la jefa del área de ventas. </div>

                <b class="mb-3">Victimario:</b>
                <div class="radio-button"> <%= f.radio_button :pregunta3, false %> a) Yo, fui la víctima de la simulación.</div>
                <div class="radio-button"> <%= f.radio_button :pregunta3, true %> b) Ricardo, el último compañero que vi en la oficina. </div>
                <div class="radio-button"> <%= f.radio_button :pregunta3, false %> c) Juan, el compañero que estaba en la oficina antes que yo. </div>

                <b class="mb-3">Testigo:</b>
                <div class="radio-button"> <%= f.radio_button :pregunta3, false %> a) Yo, fui la víctima de la simulación.</div>
                <div class="radio-button"> <%= f.radio_button :pregunta3, true %> b) Daniel, el que juega tenis de mesa. </div>
                <div class="radio-button"> <%= f.radio_button :pregunta3, false %> c) Sebastián, el que va a jugar fútbol.</div>
            </div> 

            <input type="button" name="previous" class="previous-microasalto-final" value="Atrás" />
            <input type="button" name="next" class="next-microasalto-final" value="Siguiente" />
    </fieldset>
        <fieldset>
            <h2 class="fs-title">Pregunta 4</h2>
            <h3 class="fs-subtitle">¿Alguna vez has visto en lugar de trabajo una situación similar?</h3>
            <div class ="field-buttons">
                <div class="radio-button"> <%= f.radio_button :pregunta4, true %> Si</div>
                <div class="radio-button"> <%= f.radio_button :pregunta4, false %> No</div>
                <div class="radio-button"> <%= f.radio_button :pregunta4, nil %> Quizás</div>
            </div> 
            <input type="button" name="previous" class="previous-microasalto-final" value="Atrás" />
            <%= f.submit "Enviar", class: "next-microasalto-final"%>
        </fieldset>
    </div>
<% end %>

</div>
<!-- jQuery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
<!-- jQuery easing plugin -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js" type="text/javascript"></script>

app/views/microasalto_encuesta_finals/show.html.erb
<div class='container text-center'>
<h2 class="text-4xl font-extrabold dark:text-white mb-4">Encuesta Final de Microasalto</h2>


<h2 class='text-3xl'> Resultado: <%= @encuesta.porcentaje_bueno %>/100 </h2>


<a class="block p-6 m-6 max-w bg-white rounded-lg border border-gray-200 shadow-md <%= @encuesta.pregunta1 ? 'bg-green-200' : 'bg-red-200' %>">
    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Pregunta 1: <%= @encuesta.pregunta1 ? "Correcta" : "Incorrecta" %></h5>
    <p class="font-normal text-gray-700 dark:text-gray-400">De acuerdo a la simulación, ¿qué crees que se pudo evidenciar?</p>
    <p class="font-normal text-gray-700 dark:text-gray-400">
        a) Comentario o acción discriminatoria de manera sutil. </br>
        b) Comportamiento intencional y discriminatorio sin pretensión de ofensa. </br>
        c) Minimización de experiencias ajenas. </br>
        d) No hubo ningún comentario o acción inadecuada. </br>
    </p>
    </br>
    <b>La respuesta correcta era: a) Comentario o acción discriminatoria de manera sutil.</b>
</a>


<a class="block p-6 m-6 max-w bg-white rounded-lg border border-gray-200 shadow-md <%= @encuesta.pregunta2 ? 'bg-green-200' : 'bg-red-200' %>">
    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Pregunta 2: <%= @encuesta.pregunta2 ? "Correcta" : "Incorrecta" %></h5>
    <p class="font-normal text-gray-700 dark:text-gray-400 ">
        Teniendo bajo consideración lo siguiente: </br>
        I) Comportamientos intencionales y discriminatorios sin pretensión de ofensa. </br>
        II)Menospreciar o invalidar experiencias ajenas. </br>
        III)Comentarios o acciones que son discriminatorias accidentalmente.</br></br>
        En la/s simulación/es realizada/s recientemente, cuál definición describe de mejor manera lo que usted experimentó:
    </p> 
    <p class="font-normal text-gray-700 dark:text-gray-400">
    a) Solo I </br>
    b) Solo II </br>
    c) Solo III </br>
    d) I, II </br>
    e) III, I </br>
    f) Ninguna de las anteriores. </br>

    </p>
    </br>
    <b>La respuesta correcta era: c) Solo III</b>
</a>

<a class="block p-6 m-6 max-w bg-white rounded-lg border border-gray-200 shadow-md <%= @encuesta.pregunta3 ? 'bg-green-200' : 'bg-red-200' %>">
    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Pregunta 3: <%= @encuesta.pregunta3 ? "Correcta" : "Incorrecta" %></h5>
    <p class="font-normal text-gray-700 dark:text-gray-400">¿Quién consideras que fue la persona agredida la/s simulación/es realizada/s?</p>
    <p class="font-normal text-gray-700 dark:text-gray-400">
        Víctima:</br>
            a) Yo, fui la víctima de la simulación.</br>
            b) Cristian, el gerente de la empresa. </br>
            c) Jimena, la jefa del área de ventas. </br>
        Victimario:</br>
            a) Yo, fui la víctima de la simulación.</br>
            b) Ricardo, el último compañero que vi en la oficina.</br>
            c) Juan, el compañero que estaba en la oficina antes que yo. </br>
        Testigo:</br>
            a) Yo, fui la víctima de la simulación.</br>
            b) Daniel, el que juega tenis de mesa. </br>
            c) Sebastián, el que va a jugar fútbol.</br>
    </p>
    </br>
    <b>Las respuestas correctan eran:  a) Yo, fui la víctima de la simulación, c) Juan, el compañero que estaba en la oficina antes que yo. y b) Daniel, el que juega tenis de mesa. </b>
</a>


<%= link_to "Volver", microasalto_path(user_id: @user.id),  class:" m-6 float-right text-gray-500 bg-gray-200 hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600"%>
</div>